#include "AttrDef.h"

//定义属性数据类型表

/// 和 tagGameAttributeType 对应
//如果加了新的buff类型，这里就要添加一位
TAttrDataTypes	AttrDataTypes = 
{
	adInt,				//aUndefined						= 0,	//未定义属性	
	adInt,				//aHpAdd							= 1,	//血增加
	adFloat,			//aHpPower							= 2,	//血倍率增加			
	adInt ,				//aMpAdd							= 3,	//蓝增加			
	adInt,			//aMpPower							= 4,	//蓝倍率增加		
	adInt,				//aMaxHpAdd							= 5,	//最大血增加		
	adInt,			//aMaxHpPower						= 6,	//最大血倍率增加
	adInt,				//aMaxMpAdd							= 7,	//最大蓝增加
	adInt,			//aMaxMpPower						= 8,	//最大蓝倍率增加
	adInt,				//aPhysicalAttackMinAdd				= 9,	//最小物理攻击增加
	adInt,			//aPhysicalAttackMinPower			= 10,	//最小物理攻击倍率增加
	adInt,				//aPhysicalAttackMaxAdd				= 11,	//最大物理攻击增加
	adInt,			//aPhysicalAttackMaxPower			= 12,	//最大物理攻击倍率增加
	adInt,				//aMagicAttackMinAdd				= 13,	//最小魔法攻击增加
	adInt,			//aMagicAttackMinPower				= 14,	//最小魔法攻击倍率增加
	adInt,				//aMagicAttackMaxAdd				= 15,	//最大魔法攻击增加
	adInt,			//aMagicAttackMaxPower				= 16,	//最大魔法攻击倍率增加
	adInt,				//aWizardAttackMinAdd				= 17,	//最小道术攻击增加
	adInt,			//aWizardAttackMinPower				= 18,	//最小道术攻击倍率增加
	adInt,				//aWizardAttackMaxAdd				= 19,	//最大道术攻击增加
	adInt,			//aWizardAttackMaxPower				= 20,	//最大道术攻击倍率增加
	adInt,				//aPhysicalDefenceMinAdd			= 21,	//最小物理防御增加
	adInt,			//aPhysicalDefenceMinPower			= 22,	//最小物理防御倍率增加
	adInt,				//aPhysicalDefenceMaxAdd			= 23,	//最大物理防御增加
	adInt,			//aPhysicalDefenceMaxPower			= 24,	//最大物理防御倍率增加
	adInt,				//aMagicDefenceMinAdd				= 25,	//最小魔法防御增加
	adInt,			//aMagicDefenceMinPower				= 26,	//最小魔法防御倍率增加
	adInt,				//aMagicDefenceMaxAdd				= 27,	//最大魔法防御增加
	adInt,			//aMagicDefenceMaxPower				= 28,	//最大魔法防御倍率增加
	adInt,				//aHitValueAdd						= 29,	//物理命中增加
	adInt,			//aHitValuePower					= 30,	//物理命中倍率增加
	adInt,				//aDogValueAdd						= 31,	//物理闪避增加
	adInt,			//aDogValuePower					= 32,	//物理闪避倍率增加
	adInt,				//aMagicHitRateAdd					= 33,	//魔法命中增加
	adInt,			//aMagicHitRatePower				= 34,	//魔法命中倍率增加
	adInt,				//aMagicDogerateAdd					= 35,	//魔法闪避增加
	adInt,			//aMagicDogeratePower				= 36,	//魔法闪避倍率增加
	adInt,			//aHpRenewRateAdd					= 37,	//生命恢复百分比增加          (注意，这才是加HP恢复百分比，会影响PROP_CREATURE_HP_RENEW)
	adInt,			//aHpRenewRatePower					= 38,	//生命恢复百分比倍率增加
	adInt,			//aMpRenewRateAdd					= 39,	//魔法恢复百分比增加          (注意，这才是加MP恢复百分比，会影响PROP_CREATURE_MP_RENEW)
	adInt,			//aMpRenewRatePower					= 40,	//魔法恢复百分比倍率增加
	adInt,				//aMoveSpeedAdd						= 41,	//移动速度增加
	adInt,			//aMoveSpeedPower					= 42,	//移动速度倍率增加
	adInt,				//aAttackSpeedAdd					= 43,	//攻击速度增加
	adInt,			//aAttackSpeedPower					= 44,	//攻击速度倍率增加
	adInt,				//aLuckAdd							= 45,	//幸运增加
	adInt,			//aLuckPower						= 46,	//幸运倍率增加
	adInt,				//aHpRenewAdd						= 47,	//生命恢复增加
	adInt,			//aHpRenewPower						= 48,	//生命恢复倍率增加
	adInt,				//aMpRenewAdd						= 49,	//魔法恢复增加 
	adInt,			//aMpRenewPower						= 50,	//魔法恢复倍率增加
	adInt,				//									= 51,	//
	adFloat,			//									= 52,	//

	adInt ,				//aDamageAbsorb						= 53,   //[BUFF] 伤害抵消的BUFF状态 ( value:池值,  param:吸收万分比 )
	adInt,				//aDamageAbsorbRate					= 54,	//[NORMAL] 伤害减免,万分比
	adInt,				//aDizzy							= 55,	//[BUFF] 麻痹，不可移动，不可释放技能 ( 无参 )
	adInt,              //aExpAdd							= 56,   //[NORMAL] 经验增加一个数值 ( 物品<value:经验> )
	adInt,              //aHpCure							= 57,	//[BUFF] 治愈的BUFF状态  ( value:池值,  param1:每次回复量 )
	adInt,				//aHide								= 58,   //[BUFF] 隐身状态 ( 无参 )
	adInt,          	//aExpPower							= 59,   //[NORMAL] 经验的增加倍率，万分比
	adInt,              //aFreeze							= 60,	//[BUFF] 冻结，只能走，不能跑
	adInt,              //aPkProtectState					= 61,   //[BUFF] pk保护状态
	adInt,				//aRealFreeze						= 62,	//[BUFF] 真·冻结，不能走不能跑
	adInt,              //aMpCure							= 63,   //[BUFF] 持续回蓝的BUFF状态  ( value:池值,  param1:每次回复量 )
	adInt,        	    //aMpReplaceHpRate					= 64,   //[NORMAL] 按比例将MP抵消HP，万分比
	adInt,				//aDizzyRateAdd						= 65,   //[NORMAL] 麻痹概率，万分比
	adInt,				//aDeductDizzyRate					= 66,	//[BUFF] 抗麻痹概率，万分比
	adInt,              //aDizzyTimeAdd						= 67,	//[BUFF] 麻痹时长增加
	adInt,              //aDizzyTimeAbsorbAdd				= 68,	//[BUFF] 麻痹时长减免
	adInt,              //aGuardRate						= 69,	//[BUFF] 守护概率，万分比
	adInt,				//aCuttingRate						= 70,	//[BUFF] 切割概率，万分比
	adInt,       		//aGuardValue					 	= 71,	//守护成功减免血量
	adInt,              //aNextSkillFlag					= 72,	//[战士技能标记] 战士延次技能的标志（标记战士的下一次附加技能：攻杀，刺杀，半月，烈火，逐日）
	adFloat,            //aDieRefreshHpPro					= 73,   //死亡以后立刻回复的HP的比例,1点表示百分之1(复活戒指使用)
	adInt,				//aNewPlayerProtect					= 74,	//新手保护*************buffSystem使用**********
	adInt,				//aDoubleAtkRate					= 75,   //倍攻率 万分比
	adInt,              //aAllAttackMinAdd					= 76, 	//最小全属性攻击增加
	adInt,              //aAllAttackMaxAdd					= 77,	//最大全属性攻击增加
	adFloat,            //aForbidHpRenew					= 78,	//[BUFF] 禁止回血的BUFF状态
	adInt,           	//aSuckBloodRate					= 79,   //吸血
	adInt,              //aAllAttackAddRate					= 80,   //攻魔道属性增加 万分比
	adInt,            	//aDoubleDefenseRate				= 81,   //双防加成 万分比
	adInt,			    //aIgnorDefenceRatio				= 82,   //无视双防比例 万分比
	adInt,				//aNormalAttackAcc					= 83,	//[NORMAL] 普攻加速度，万分比
	adInt,            //aPkDamageAbsorbRate					= 84,	//pk伤害减免 万分比
	adInt,            //aSaviorTime						= 85,	//救主灵刃-CD时间
	adInt,            //aSaviorRate						= 86,	//救主灵刃-回复率
	adInt,            //aSaviorValue						= 87,	//救主灵刃-回复值
	adInt,            //aToxicRate						= 88,	//剧毒几率
	adInt,            //aToxicDamage						= 89,	//剧毒伤害
	adInt,			//aToxicEffect						= 90,	//剧毒效果
	adInt,			//aFrozenStrength					= 91,	//冰冻强度
	adInt,				//aFireDefenseRate					= 92,	//抗火率 使用1点表示1万分之1
	adInt,				//aReduceEquipDropRate				= 93,	//减少玩家死亡爆装备几率 使用1点表示1万分之1
	adInt,              //aDamageDropTime					= 94,	//收到伤害以后，状态时间减少，当buff删除的时候使用技能*************buffSystem使用**********
	adInt,              //aWarriorDamageValueDec			= 95,	//固定值降低战士的伤害
	adInt,              //aWarriorDamageRateDec				= 96,	//百分比降低战士的伤害
	adInt,              //aMagicianDamageValueDesc			= 97,	//固定值降低法师的伤害
	adInt,			    //aMagicianDamageRateDesc			= 98,	//固定比降低法师的伤害
	adInt,              //aWizardDamageValueDesc			= 99,	//固定值降低道士的伤害
	adInt,			    //aWizardDamageRateDesc				= 100,	//固定比降低法师的伤害
	adInt,              //aMonsterDamageValueDesc			= 101,  //固定值降低怪物的伤害
	adInt,			    //aMonsterDamageRateDesc			= 102,	//固定比降低怪物的伤害
	adInt,              //aDamageReduceRate					= 103,	//触发伤害减免的几率
	adInt,			    //aDamageReduceValue				= 104,	//触发伤害减免的值
	adInt,              //aDamageAddRate					= 105,	//触发伤害追加的几率
	adInt,			    //aDamageAddValue					= 106,	//触发伤害追加的值
	adInt,              //aIgnorDefenceRateSkill			= 107,	//技能触发无视防御几率
	adInt,			    //aIgnorDefenceRate					= 108,  //触发无视防御几率
	adFloat,			//a109								= 109,
	adInt,				//aWarriorTargetDamageValue			= 110,  //固定值增加对战士的伤害
	adInt,				//aWarriorTargetDamageRate			= 111,  //百分比增加对战士的伤害
	adInt,				//aMagicianTargetDamageValue		= 112,  //固定值增加对法师的伤害
	adInt,				//aMagicianTargetDamageRate			= 113,	//固定比增加对法师的伤害
	adInt,				//aWizardTargetDamageValue			= 114,  //固定值增加对道士的伤害
	adInt,				//aWizardTargetDamageRate			= 115,	//固定比增加对法师的伤害
	adInt,				//aMonsterTargetDamageValue			= 116,  //固定值增加对怪物的伤害
	adInt,				//aMonsterTargetDamageRate			= 117,	//固定比增加对怪物的伤害
	adFloat,			//aHPMPDeductPower					= 118,	//吃药效果减百分率
	adInt,				//aAddAllDamageRate					= 119,	//攻击时候附加攻击输出的概率,整数配置，1点表示万分之1
	adFloat,			//aAddAllDamagePower				= 120,	//攻击时附加攻击输出的倍率增加
	adInt,				//aAddDamageReboundRate				= 121,  //伤害反弹 概率,整数配置，1点表示万分之1
	adFloat,			//aAddDamageReboundPower			= 122,	//伤害反弹 倍率
	adInt,				//aAddAllDamageRateEx				= 123,  //会心一击附加攻击输出的概率,整数配置，1点表示万分之1
	adInt,				//aChangeMonsterModle				= 124,	//新的变身属性
	adInt,				//aFixed						    = 125,	//定身,不可移动，可释放技能*************buffSystem使用**********
	adInt,              //aSelfAddBuffRate					= 126,	//造成伤害时，自己获得buff的几率（万分比）
	adInt,              //aSelfAddBuffId					= 127,	//造成伤害时，自己获得buff的Id
	adInt,              //aTargetAddBuffRate				= 128,	//造成伤害时, 目标获得buff的几率（万分比）
	adInt,              //aTargetAddBuffId					= 129,	//造成伤害时, 目标获得buff的Id
	adInt,				//aBuffChangeModel					= 130,  //变身状态，bufff改变模型Id
	adInt,				//a131								= 131,	//
	adInt,				//aSlient							= 132,  //沉默(不能使用技能)*************buffSystem使用**********
	adInt,				//a133								= 133,	//
	adInt,				//aExpAddRate						= 134,	//根据库加经验
	adFloat,			//a135								= 135,
	adInt,				//aCritDamagePower					= 136,	//暴击力万分比
	adUInt,				//aHpMpAdd					    	= 137,	//回血回蓝
	adInt,				//aCritDamageRate					= 138,  //暴击几率（新）区别于119
	adInt,				//aCritDamageValue					= 139,	//暴击力（新）区别于120,原来伤害基础上最后加上aCritDamagePower的伤害
	adInt,				//aaDeductCriteDamageRate			= 140， //抗暴
	adInt,				//aFastMedicamentRenew				= 141,  //速回药品回复率
	adUInt,				//aBuffExpAdd						= 142, //增加经验buff
	adFloat,			//aBuffHeroExpRate					= 143,	//英雄增加经验buff
	adInt,				//aBuffmtBindCoinAddRate			= 144,  //拾取金币加成buff
	adInt,			    //aHalfMonthsIncreaseDamage			= 145,	//半月增伤
	adInt,			    //aFireIncreaseDamage				= 146,	//烈火增伤
	adInt,			    //aDayByDayIncreaseDamage			= 147,	//逐日增伤
	adInt,			    //aIceStormIncreaseDamage			= 148,	//冰咆哮增伤
	adInt,			    //aFireRainIncreaseDamage			= 149,	//火雨增伤
	adInt,			    //aThunderIncreaseDamage			= 150,	//雷电增伤
	adInt,			    //aBloodBiteIncreaseDamage			= 151,	//噬血术增伤
	adInt,			    //aFireSignIncreaseDamage			= 152,	//火符增伤
	adInt,			    //aHalfMonthsReduceDamage			= 153,	//半月减伤
	adInt,			    //aFireReduceDamage					= 154,	//烈火减伤
	adInt,			    //aDayByDayReduceDamage				= 155,	//逐日减伤
	adInt,			    //aIceStormReduceDamage				= 156,	//冰咆哮减伤
	adInt,			    //aFireRainReduceDamage				= 157,	//火雨减伤
	adInt,			    //aThunderReduceDamage				= 158,	//雷电减伤
	adInt,			    //aBloodBiteReduceDamage			= 159,	//噬血术减伤
	adInt,			    //aFireSignReduceDamage				= 160,	//火符减伤
};
static_assert(sizeof(AttrDataTypes)/sizeof(eAttribueTypeDataType) == GameAttributeCount, "AttrDataTypes 长度应跟 tagGameAttributeType 保持一致");

//定义属性是否需要通过属性计算器计算属性的标志表，和tagGameAttributeType对应
TAttrNeedCalc	AttrNeedCalc =
{
	false,		//aUndefined						= 0,	//未定义属性	
	false,		//aHpAdd							= 1,	//血增加
	false,		//aHpPower							= 2,	//血倍率增加			
	false ,		//aMpAdd							= 3,	//蓝增加			
	false,		//aMpPower							= 4,	//蓝倍率增加		
	true,		//aMaxHpAdd							= 5,	//最大血增加		
	true,		//aMaxHpPower						= 6,	//最大血倍率增加
	true,		//aMaxMpAdd							= 7,	//最大蓝增加
	true,		//aMaxMpPower						= 8,	//最大蓝倍率增加
	true,		//aPhysicalAttackMinAdd				= 9,	//最小物理攻击增加
	true,	    //aPhysicalAttackMinPower			= 10,	//最小物理攻击倍率增加
	true,		//aPhysicalAttackMaxAdd				= 11,	//最大物理攻击增加
	true,		//aPhysicalAttackMaxPower			= 12,	//最大物理攻击倍率增加
	true,		//aMagicAttackMinAdd				= 13,	//最小魔法攻击增加
	true,		//aMagicAttackMinPower				= 14,	//最小魔法攻击倍率增加
	true,		//aMagicAttackMaxAdd				= 15,	//最大魔法攻击增加
	true,		//aMagicAttackMaxPower				= 16,	//最大魔法攻击倍率增加
	true,		//aWizardAttackMinAdd				= 17,	//最小道术攻击增加
	true,		//aWizardAttackMinPower				= 18,	//最小道术攻击倍率增加
	true,		//aWizardAttackMaxAdd				= 19,	//最大道术攻击增加
	true,		//aWizardAttackMaxPower				= 20,	//最大道术攻击倍率增加
	true,		//aPhysicalDefenceMinAdd			= 21,	//最小物理防御增加
	true,		//aPhysicalDefenceMinPower			= 22,	//最小物理防御倍率增加
	true,		//aPhysicalDefenceMaxAdd			= 23,	//最大物理防御增加
	true,		//aPhysicalDefenceMaxPower			= 24,	//最大物理防御倍率增加
	true,		//aMagicDefenceMinAdd				= 25,	//最小魔法防御增加
	true,		//aMagicDefenceMinPower				= 26,	//最小魔法防御倍率增加
	true,		//aMagicDefenceMaxAdd				= 27,	//最大魔法防御增加
	true,		//aMagicDefenceMaxPower				= 28,	//最大魔法防御倍率增加
	true,		//aHitValueAdd						= 29,	//物理命中增加
	true,		//aHitValuePower					= 30,	//物理命中倍率增加
	true,		//aDogValueAdd						= 31,	//物理闪避增加
	true,		//aDogValuePower					= 32,	//物理闪避倍率增加
	true,		//aMagicHitRateAdd					= 33,	//魔法命中增加
	true,		//aMagicHitRatePower				= 34,	//魔法命中倍率增加
	true,		//aMagicDogerateAdd					= 35,	//魔法闪避增加
	true,		//aMagicDogeratePower				= 36,	//魔法闪避倍率增加
	true,		//aHpRenewRateAdd					= 37,	//生命恢复百分比增加              (注意，这才是加HP恢复百分比，会影响PROP_CREATURE_HP_RENEW)
	true,		//aHpRenewRatePower					= 38,	//生命恢复百分比倍率增加
	true,		//aMpRenewRateAdd					= 39,	//魔法恢复百分比增加              (注意，这才是加MP恢复百分比，会影响PROP_CREATURE_MP_RENEW)
	true,		//aMpRenewRatePower					= 40,	//魔法恢复百分比倍率增加
	true,		//aMoveSpeedAdd						= 41,	//移动速度增加
	true,		//aMoveSpeedPower					= 42,	//移动速度倍率增加
	true,		//aAttackSpeedAdd					= 43,	//攻击速度增加
	true,		//aAttackSpeedPower					= 44,	//攻击速度倍率增加
	true,		//aLuckAdd							= 45,	//幸运增加
	true,		//aLuckPower						= 46,	//幸运倍率增加
	true,		//aHpRenewAdd						= 47,	//生命恢复增加
	true,		//aHpRenewPower						= 48,	//生命恢复倍率增加
	true,		//aMpRenewAdd						= 49,	//魔法恢复增加 
	true,		//aMpRenewPower						= 50,	//魔法恢复倍率增加
	true,		//									= 51,	//
	true,		//									= 52,	//

	false ,		//aDamageAbsorb						= 53,   //[BUFF] 伤害抵消的BUFF状态 ( value:池值,  param:吸收万分比 )
	true,		//aDamageAbsorbRate					= 54,	//[NORMAL] 伤害减免,万分比
	false,		//aDizzy							= 55,	//[BUFF] 麻痹，不可移动，不可释放技能 ( 无参 )
	false,      //aExpAdd							= 56,   //[NORMAL] 经验增加一个数值 ( 物品<value:经验> )
	false,      //aHpCure							= 57,	//[BUFF] 治愈的BUFF状态  ( value:池值,  param1:每次回复量 )
	false,		//aHide								= 58,   //[BUFF] 隐身状态 ( 无参 )
	true,       //aExpPower							= 59,   //[NORMAL] 经验的增加倍率，万分比
	false,      //aFreeze							= 60,	//[BUFF] 冻结，只能走，不能跑
	false,      //aPkProtectState					= 61,   //[BUFF] pk保护状态
	true,		//aRealFreeze						= 62,	//[BUFF] 真·冻结，不能走不能跑
	true,       //aMpCure							= 63,	//[BUFF] 持续回蓝的BUFF状态  ( value:池值,  param1:每次回复量 )
	true,       //aMpReplaceHpRate					= 64,   //[NORMAL] 按比例将MP抵消HP，万分比
	true,		//aDizzyRateAdd						= 65,   //[NORMAL] 麻痹概率，万分比
	true,		//aDeductDizzyRate					= 66,	//[BUFF] 抗麻痹概率，万分比
	true,       //aDizzyTimeAdd						= 67,	//[BUFF] 麻痹时长增加
	true,       //aDizzyTimeAbsorbAdd				= 68,	//[BUFF] 麻痹时长减免
	true,       //aGuardRate						= 69,	//[BUFF] 守护概率，万分比
	true,		//aCuttingRate						= 70,	//[BUFF] 切割概率，万分比
	true,       //aGuardValue					 	= 71,	//守护成功减免血量
	false,      //aNextSkillFlag					= 72,	//[战士技能标记] 战士延次技能的标志（标记战士的下一次附加技能：攻杀，刺杀，半月，烈火，逐日）
	true,       //aDieRefreshHpPro					= 73,   //死亡以后立刻回复的HP的比例,1点表示百分之1(复活戒指使用)
	false,		//aNewPlayerProtect					= 74,	//新手保护*************buffSystem使用**********
	true,		//aDoubleAtkRate					= 75,   //倍攻率 万分比
	true,       //aAllAttackMinAdd					= 76,	//最小全属性攻击增加
	true,       //aAllAttackMaxAdd					= 77,	//最大全属性攻击增加
	true,       //aForbidHpRenew					= 78,	//[BUFF] 禁止回血的BUFF状态
	true,       //aSuckBloodRate					= 79,   //吸血
	true,       //a_80								= 80,
	true,       //a_81								= 81,
	true,		//a_82								= 82,
	true,		//a_83								= 83,
	true,       //a_84								= 84,
	true,       //aSaviorTime						= 85,	//救主灵刃-CD时间
	true,       //aSaviorRate						= 86,	//救主灵刃-回复率
	true,       //aSaviorValue						= 87,	//救主灵刃-回复值
	true,       //aToxicRate						= 88,	//剧毒几率
	true,       //aToxicDamage						= 89,	//剧毒伤害
	true,		//aToxicEffect						= 90,	//剧毒效果
	true,		//aFrozenStrength					= 91,	//冰冻强度
	true,		//aFireDefenseRate					= 92,	//抗火率 使用1点表示1万分之1
	true,		//aReduceEquipDropRate				= 93,	//减少玩家死亡爆装备几率 使用1点表示1万分之1
	false,      //aDamageDropTime					= 94,	//收到伤害以后，状态时间减少，当buff删除的时候使用技能*************buffSystem使用**********
	true,       //aWarriorDamageValueDec			= 95,	//固定值降低战士的伤害
	true,       //aWarriorDamageRateDec				= 96,	//百分比降低战士的伤害
	true,       //aMagicianDamageValueDesc			= 97,	//固定值降低法师的伤害
	true,		//aMagicianDamageRateDesc			= 98,	//固定比降低法师的伤害
	true,       //aWizardDamageValueDesc			= 99,	//固定值降低道士的伤害
	true,		//aWizardDamageRateDesc				= 100,	//固定比降低法师的伤害
	true,       //aMonsterDamageValueDesc			= 101,  //固定值降低怪物的伤害
	true,		//aMonsterDamageRateDesc			= 102,	//固定比降低怪物的伤害
	true,       //aDamageReduceRate					= 103,	//触发伤害减免的几率
	true,		//aDamageReduceValue				= 104,	//触发伤害减免的值
	true,       //aDamageAddRate					= 105,	//触发伤害追加的几率
	true,		//aDamageAddValue					= 106,	//触发伤害追加的值
	true,       //aIgnorDefenceRateSkill			= 107,	//技能触发无视防御几率
	true,		//aIgnorDefenceRate					= 108,  //触发无视防御几率
	true,		//a109								= 109,
	true,		//aWarriorTargetDamageValue			= 110,  //固定值增加对战士的伤害
	true,		//aWarriorTargetDamageRate			= 111,  //百分比增加对战士的伤害
	true,		//aMagicianTargetDamageValue		= 112,  //固定值增加对法师的伤害
	true,		//aMagicianTargetDamageRate			= 113,	//固定比增加对法师的伤害
	true,		//aWizardTargetDamageValue			= 114,  //固定值增加对道士的伤害
	true,		//aWizardTargetDamageRate			= 115,	//固定比增加对法师的伤害
	true,		//aMonsterTargetDamageValue			= 116,  //固定值增加对怪物的伤害
	true,		//aMonsterTargetDamageRate			= 117,	//固定比增加对怪物的伤害
	false,		//aHPMPDeductPower					= 118,	//吃药效果减百分率
	true,		//aAddAllDamageRate					= 119,	//攻击时候附加攻击输出的概率,整数配置，1点表示万分之1
	true,		//aAddAllDamagePower				= 120,	//攻击时附加攻击输出的倍率增加
	true,		//aAddDamageReboundRate				= 121,  //伤害反弹 概率,整数配置，1点表示万分之1
	true,		//aAddDamageReboundPower			= 122,	//伤害反弹 倍率
	true,		//aAddAllDamageRateEx				= 123,  //会心一击附加攻击输出的概率,整数配置，1点表示万分之1
	false,		//aChangeMonsterModle				= 124,  //新的变身属性
	false,		//aFixed						    = 125,	//定身,不可移动，可释放技能*************buffSystem使用**********
	true,       //aSelfAddBuffRate					= 126,	//造成伤害时，自己获得buff的几率（万分比）
	true,       //aSelfAddBuffId					= 127,	//造成伤害时，自己获得buff的Id
	true,       //aTargetAddBuffRate				= 128,	//造成伤害时, 目标获得buff的几率（万分比）
	true,       //aTargetAddBuffId					= 129,	//造成伤害时, 目标获得buff的Id
	true,       //aBuffChangeModel					= 130,  //变身状态，bufff改变模型Id
	false,		//a131								= 131,	//
	false,      //aSlient							= 132,  //沉默(不能使用技能)*************buffSystem使用**********
	true,		//a133								= 133,	//
	false,		//aExpAddRate						= 134,  //根据库加经验		
	true,		//a135								= 135,
	true,       //aCritDamagePower					= 136,	//暴击力万分比
	false,		//aHpMpAdd							= 137,	//回血回蓝
	true,		//aCritDamageRate					= 138,	//暴击几率（新）区别于119，(万分比)
	true,		//aCritDamageValue					= 139,	//暴击力（新）区别于120,原来伤害基础上最后加上aCritDamagePower的伤害
	true,		//aaDeductCriteDamageRate			= 140,  //抗暴
	true,		//aFastMedicamentRenew				= 141,	//速回药品回复率
	false,		//aBuffExpAdd						= 142, //增加经验buff
	true,		//aBuffHeroExpRate					= 143,	//英雄增加经验buff
	true,       //aBuffmtBindCoinAddRate	    	= 144,  //拾取金币加成buff
	true,		//aHalfMonthsIncreaseDamage			= 145,	//半月增伤
	true,		//aFireIncreaseDamage				= 146,	//烈火增伤
	true,		//aDayByDayIncreaseDamage			= 147,	//逐日增伤
	true,		//aIceStormIncreaseDamage			= 148,	//冰咆哮增伤
	true,		//aFireRainIncreaseDamage			= 149,	//火雨增伤
	true,		//aThunderIncreaseDamage			= 150,	//雷电增伤
	true,		//aBloodBiteIncreaseDamage			= 151,	//噬血术增伤
	true,		//aFireSignIncreaseDamage			= 152,	//火符增伤
	true,		//aHalfMonthsReduceDamage			= 153,	//半月减伤
	true,		//aFireReduceDamage					= 154,	//烈火减伤
	true,		//aDayByDayReduceDamage				= 155,	//逐日减伤
	true,		//aIceStormReduceDamage				= 156,	//冰咆哮减伤
	true,		//aFireRainReduceDamage				= 157,	//火雨减伤
	true,		//aThunderReduceDamage				= 158,	//雷电减伤
	true,		//aBloodBiteReduceDamage			= 159,	//噬血术减伤
	true,		//aFireSignReduceDamage				= 160,	//火符减伤
};
static_assert(sizeof(AttrNeedCalc)/sizeof(bool) == GameAttributeCount, "AttrNeedCalc 长度应跟 tagGameAttributeType 保持一致");
const double tagPackedGameAttribute::FloatValueBase = 0.0001;
